import './Items.tests'
import '../choice/tests/Choice.tests'
import '../highlight/tests/Highlight.tests'
import '../text/tests/Cloze.tests'
import '../interactive/tests/Connect.tests'
import '../sort/tests/Sort.tests'
import './validateItemDefinition.tests'
