name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lintcode:
    name: Javascript lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: setup node
      uses: actions/setup-node@v7
      with:
        node-version: 22

    - name: cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-22-

    - run: |
        cd test-proxy
        npm ci
        npm run lint:code


  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    needs: [lintcode]
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: '3.4'

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - run: |
          cd test-proxy
          npm ci
          npm run setup
          npm run test:ci
